package edu.byuh.cis.hundredsurnamesvisualization;


import android.content.res.Resources;
import android.graphics.Bitmap;
import android.graphics.BitmapFactory;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;

public class ImageCache {

//    private static Bitmap empty;

    private static Bitmap april_space_six_comma_space_one_eight_three_zero;
    private static Bitmap may_space_one_one_comma_space_one_eight_four_three;
    private static Bitmap may_space_one_comma_space_one_eight_four_four;
    private static Bitmap september_space_two_five_comma_space_one_eight_five_zero;
    private static Bitmap december_space_one_two_comma_space_one_eight_five_zero;
    private static Bitmap january_space_two_six_comma_space_one_eight_six_five;
    private static Bitmap october_space_one_eight_six_five;
    private static Bitmap october_space_one_six_comma_space_one_eight_seven_five;
    private static Bitmap june_space_one_comma_space_one_nine_one_five;
    private static Bitmap november_space_two_seven_comma_space_one_nine_one_nine;
    private static Bitmap february_space_seven_comma_space_one_nine_two_one;
    private static Bitmap april_space_nine_comma_space_one_nine_five_one;
    private static Bitmap july_space_two_one_comma_space_one_nine_five_four;
    private static Bitmap february_space_one_two_comma_space_one_nine_five_five;
    private static Bitmap september_space_one_comma_space_one_nine_five_five;
    private static Bitmap september_space_two_six_comma_space_one_nine_five_five;
    private static Bitmap december_space_one_nine_five_five;
    private static Bitmap january_space_one_nine_five_six;
    private static Bitmap june_space_one_comma_space_one_nine_five_six;
    private static Bitmap december_space_one_seven_comma_space_one_nine_five_eight;
    private static Bitmap march_space_one_nine_five_nine;
    private static Bitmap august_space_two_one_comma_space_one_nine_five_nine;
    private static Bitmap august_space_one_nine_five_nine;
    private static Bitmap january_space_one_nine_six_zero;
    private static Bitmap march_space_one_nine_six_zero;
    private static Bitmap february_space_two_three_comma_space_one_nine_six_one;
    private static Bitmap june_space_three_comma_space_one_nine_six_one;
    private static Bitmap early_space_one_nine_six_two;
    private static Bitmap february_space_one_nine_comma_space_one_nine_six_three;
    private static Bitmap october_space_one_two_comma_space_one_nine_six_three;
    private static Bitmap august_space_two_comma_space_one_nine_six_four;
    private static Bitmap october_space_one_nine_six_four;
    private static Bitmap january_space_one_nine_six_eight;
    private static Bitmap february_space_one_seven_comma_space_one_nine_six_nine;
    private static Bitmap may_space_one_five_comma_space_one_nine_six_nine;
    private static Bitmap february_space_one_one_comma_space_one_nine_seven_two;
    private static Bitmap january_space_two_six_comma_space_one_nine_seven_three;
    private static Bitmap april_space_one_three_comma_space_one_nine_seven_four;
    private static Bitmap june_space_one_nine_seven_four;
    private static Bitmap february_space_one_three_comma_space_one_nine_seven_six;
    private static Bitmap october_space_two_zero_comma_space_one_nine_seven_six;
    private static Bitmap january_space_two_three_comma_space_one_nine_seven_seven;
    private static Bitmap march_space_one_nine_comma_space_one_nine_eight_zero;
    private static Bitmap june_space_four_comma_space_one_nine_eight_zero;
    private static Bitmap august_space_one_comma_space_one_nine_eight_zero;
    private static Bitmap september_space_one_nine_eight_one;
    private static Bitmap january_space_seven_comma_space_one_nine_eight_four;
    private static Bitmap july_space_one_comma_space_one_nine_eight_six;
    private static Bitmap june_space_one_nine_eight_eight;
    private static Bitmap june_space_one_five_comma_space_one_nine_eight_eight;
    private static Bitmap september_space_one_nine_nine_one;
    private static Bitmap october_space_five_comma_space_one_nine_nine_two;
    private static Bitmap november_space_one_nine_nine_four;
    private static Bitmap february_space_one_two_comma_space_one_nine_nine_eight;
    private static Bitmap january_space_one_one_comma_space_two_zero_zero_one;
    private static Bitmap february_space_eight_comma_space_two_zero_zero_one;
    private static Bitmap november_space_three_comma_space_two_zero_zero_one;
    private static Bitmap november_space_one_five_comma_space_two_zero_zero_two;
    private static Bitmap april_space_two_five_comma_space_two_zero_zero_three;
    private static Bitmap may_space_one_two_comma_space_two_zero_zero_three;
    private static Bitmap may_space_one_six_comma_space_two_zero_zero_three;
    private static Bitmap october_space_two_five_comma_space_two_zero_zero_three;
    private static Bitmap may_space_two_one_comma_space_two_zero_zero_four;
    private static Bitmap june_space_one_nine_comma_space_two_zero_zero_four;
    private static Bitmap december_space_two_comma_space_two_zero_zero_four;
    private static Bitmap january_space_two_zero_zero_five;
    private static Bitmap february_space_two_four_comma_space_two_zero_zero_five;
    private static Bitmap april_space_one_two_comma_space_two_zero_zero_five;
    private static Bitmap may_space_two_three_comma_space_two_zero_zero_five;
    private static Bitmap august_space_one_nine_comma_space_two_zero_zero_five;
    private static Bitmap september_space_two_zero_comma_space_two_zero_zero_five;
    private static Bitmap october_space_one_six_dash_two_three_comma_space_two_zero_zero_five;
    private static Bitmap june_space_five_comma_space_two_zero_zero_seven;
    private static Bitmap august_space_two_four_comma_space_two_zero_zero_seven;
    private static Bitmap november_space_seven_comma_space_two_zero_zero_seven;
    private static Bitmap april_space_one_zero_comma_space_two_zero_zero_eight;
    private static Bitmap november_space_six_comma_space_two_zero_zero_eight;
    private static Bitmap december_space_one_seven_comma_space_two_zero_zero_eight;
    private static Bitmap january_space_two_five_comma_space_two_zero_zero_nine;
    private static Bitmap march_space_one_one_comma_space_two_zero_zero_nine;
    private static Bitmap april_space_four_comma_space_two_zero_zero_nine;
    private static Bitmap april_space_two_eight_comma_space_two_zero_zero_nine;
    private static Bitmap may_space_one_two_comma_space_two_zero_zero_nine;
    private static Bitmap july_space_two_seven_comma_space_two_zero_zero_nine;
    private static Bitmap july_space_two_seven_comma_space_two_zero_zero_nine_duplicate_zero;
    private static Bitmap september_space_one_seven_comma_space_two_zero_zero_nine;
    private static Bitmap october_space_two_zero_zero_nine;
    private static Bitmap november_space_five_comma_space_two_zero_zero_nine;
    private static Bitmap november_space_two_two_comma_space_two_zero_zero_nine;
    private static Bitmap january_space_six_comma_space_two_zero_one_zero;
    private static Bitmap may_space_two_comma_space_two_zero_one_zero;
    private static Bitmap may_space_two_zero_one_zero;
    private static Bitmap july_space_two_six_comma_space_two_zero_one_zero;
    private static Bitmap november_space_two_one_comma_space_two_zero_one_zero;
    private static Bitmap march_space_one_nine_comma_space_two_zero_one_one;
    private static Bitmap march_space_two_zero_one_one;
    private static Bitmap march_space_two_six_comma_space_two_zero_one_one;
    private static Bitmap april_space_two_zero_one_one;
    private static Bitmap april_space_two_six_comma_space_two_zero_one_one;
    private static Bitmap june_space_two_comma_space_two_zero_one_one;
    private static Bitmap september_space_two_zero_one_one;
    private static Bitmap september_space_two_two_comma_space_two_zero_one_one;
    private static Bitmap november_space_one_zero_comma_space_two_zero_one_one;
    private static Bitmap november_space_one_four_comma_space_two_zero_one_one;
    private static Bitmap december_space_nine_comma_space_two_zero_one_one;
    private static Bitmap december_space_one_seven_comma_space_two_zero_one_one;
    private static Bitmap december_space_two_zero_one_one;
    private static Bitmap january_space_two_zero_one_two;
    private static Bitmap march_space_eight_dash_one_one_comma_space_two_zero_one_two;
    private static Bitmap march_space_nine_comma_space_two_zero_one_two;
    private static Bitmap april_space_one_six_comma_space_two_zero_one_two;
    private static Bitmap april_space_two_three_comma_space_two_zero_one_two;
    private static Bitmap may_space_one_eight_comma_space_two_zero_one_two;
    private static Bitmap may_space_one_nine_comma_space_two_zero_one_two;
    private static Bitmap may_space_two_four_comma_space_two_zero_one_two;
    private static Bitmap september_space_one_seven_comma_space_two_zero_one_two;
    private static Bitmap september_space_two_six_comma_space_two_zero_one_two;
    private static Bitmap october_space_four_comma_space_two_zero_one_two;
    private static Bitmap october_space_one_eight_comma_space_two_zero_one_two;
    private static Bitmap november_space_two_nine_dash_december_space_one_comma_space_two_zero_one_two;
    private static Bitmap january_space_two_zero_one_three;
    private static Bitmap may_space_two_zero_one_three;
    private static Bitmap may_space_two_two_comma_space_two_zero_one_three;
    private static Bitmap june_space_one_zero_dash_two_four_comma_space_two_zero_one_three;
    private static Bitmap june_dash_august_space_two_zero_one_three;
    private static Bitmap september_space_eight_comma_space_two_zero_one_three;
    private static Bitmap october_space_two_zero_one_three;
    private static Bitmap october_space_one_one_comma_space_two_zero_one_three;
    private static Bitmap october_space_one_one_comma_space_two_zero_one_three_duplicate_one;
    private static Bitmap december_space_one_three_comma_space_two_zero_one_three;
    private static Bitmap february_space_nine_comma_space_two_zero_one_four;
    private static Bitmap march_space_one_two_dash_one_six_comma_space_two_zero_one_four;
    private static Bitmap march_space_two_eight_comma_space_two_zero_one_four;
    private static Bitmap may_space_two_zero_comma_space_two_zero_one_four;
    private static Bitmap september_space_two_zero_one_four;
    private static Bitmap september_space_two_zero_one_four_duplicate_two;
    private static Bitmap september_space_two_zero_one_four_duplicate_three;
    private static Bitmap february_space_six_dash_one_two_comma_space_two_zero_one_five;
    private static Bitmap march_space_one_one_comma_space_two_zero_one_five;
    private static Bitmap april_space_one_six_comma_space_two_zero_one_five;
    private static Bitmap may_space_one_two_comma_space_two_zero_one_five;
    private static Bitmap may_space_two_zero_one_five;
    private static Bitmap october_space_two_four_comma_space_two_zero_one_five;
    private static Bitmap october_comma_space_two_zero_one_five;
    private static Bitmap november_space_one_zero_comma_space_two_zero_one_five;


    public static void init(Resources res, float w2, float h) {
        float w = w2 / 4;

//        empty = loadAndScale(res,R.drawable.example,w);

        april_space_six_comma_space_one_eight_three_zero = loadAndScale(res, R.drawable.april_space_six_comma_space_one_eight_three_zero, w);
        may_space_one_one_comma_space_one_eight_four_three = loadAndScale(res, R.drawable.may_space_one_one_comma_space_one_eight_four_three, w);
        may_space_one_comma_space_one_eight_four_four = loadAndScale(res, R.drawable.may_space_one_comma_space_one_eight_four_four, w);
        september_space_two_five_comma_space_one_eight_five_zero = loadAndScale(res, R.drawable.september_space_two_five_comma_space_one_eight_five_zero, w);
        december_space_one_two_comma_space_one_eight_five_zero = loadAndScale(res, R.drawable.december_space_one_two_comma_space_one_eight_five_zero, w);
        january_space_two_six_comma_space_one_eight_six_five = loadAndScale(res, R.drawable.january_space_two_six_comma_space_one_eight_six_five, w);
        october_space_one_eight_six_five = loadAndScale(res, R.drawable.october_space_one_eight_six_five, w);
        october_space_one_six_comma_space_one_eight_seven_five = loadAndScale(res, R.drawable.october_space_one_six_comma_space_one_eight_seven_five, w);
        june_space_one_comma_space_one_nine_one_five = loadAndScale(res, R.drawable.june_space_one_comma_space_one_nine_one_five, w);
        november_space_two_seven_comma_space_one_nine_one_nine = loadAndScale(res, R.drawable.november_space_two_seven_comma_space_one_nine_one_nine, w);
        february_space_seven_comma_space_one_nine_two_one = loadAndScale(res, R.drawable.february_space_seven_comma_space_one_nine_two_one, w);
        april_space_nine_comma_space_one_nine_five_one = loadAndScale(res, R.drawable.april_space_nine_comma_space_one_nine_five_one, w);
        july_space_two_one_comma_space_one_nine_five_four = loadAndScale(res, R.drawable.july_space_two_one_comma_space_one_nine_five_four, w);
        february_space_one_two_comma_space_one_nine_five_five = loadAndScale(res, R.drawable.february_space_one_two_comma_space_one_nine_five_five, w);
        september_space_one_comma_space_one_nine_five_five = loadAndScale(res, R.drawable.september_space_one_comma_space_one_nine_five_five, w);
        september_space_two_six_comma_space_one_nine_five_five = loadAndScale(res, R.drawable.september_space_two_six_comma_space_one_nine_five_five, w);
        december_space_one_nine_five_five = loadAndScale(res, R.drawable.december_space_one_nine_five_five, w);
        january_space_one_nine_five_six = loadAndScale(res, R.drawable.january_space_one_nine_five_six, w);
        june_space_one_comma_space_one_nine_five_six = loadAndScale(res, R.drawable.june_space_one_comma_space_one_nine_five_six, w);
        december_space_one_seven_comma_space_one_nine_five_eight = loadAndScale(res, R.drawable.december_space_one_seven_comma_space_one_nine_five_eight, w);
        march_space_one_nine_five_nine = loadAndScale(res, R.drawable.march_space_one_nine_five_nine, w);
        august_space_two_one_comma_space_one_nine_five_nine = loadAndScale(res, R.drawable.august_space_two_one_comma_space_one_nine_five_nine, w);
        august_space_one_nine_five_nine = loadAndScale(res, R.drawable.august_space_one_nine_five_nine, w);
        january_space_one_nine_six_zero = loadAndScale(res, R.drawable.january_space_one_nine_six_zero, w);
        march_space_one_nine_six_zero = loadAndScale(res, R.drawable.march_space_one_nine_six_zero, w);
        february_space_two_three_comma_space_one_nine_six_one = loadAndScale(res, R.drawable.february_space_two_three_comma_space_one_nine_six_one, w);
        june_space_three_comma_space_one_nine_six_one = loadAndScale(res, R.drawable.june_space_three_comma_space_one_nine_six_one, w);
        early_space_one_nine_six_two = loadAndScale(res, R.drawable.early_space_one_nine_six_two, w);
        february_space_one_nine_comma_space_one_nine_six_three = loadAndScale(res, R.drawable.february_space_one_nine_comma_space_one_nine_six_three, w);
        october_space_one_two_comma_space_one_nine_six_three = loadAndScale(res, R.drawable.october_space_one_two_comma_space_one_nine_six_three, w);
        august_space_two_comma_space_one_nine_six_four = loadAndScale(res, R.drawable.august_space_two_comma_space_one_nine_six_four, w);
        october_space_one_nine_six_four = loadAndScale(res, R.drawable.october_space_one_nine_six_four, w);
        january_space_one_nine_six_eight = loadAndScale(res, R.drawable.january_space_one_nine_six_eight, w);
        february_space_one_seven_comma_space_one_nine_six_nine = loadAndScale(res, R.drawable.february_space_one_seven_comma_space_one_nine_six_nine, w);
        may_space_one_five_comma_space_one_nine_six_nine = loadAndScale(res, R.drawable.may_space_one_five_comma_space_one_nine_six_nine, w);
        february_space_one_one_comma_space_one_nine_seven_two = loadAndScale(res, R.drawable.february_space_one_one_comma_space_one_nine_seven_two, w);
        january_space_two_six_comma_space_one_nine_seven_three = loadAndScale(res, R.drawable.january_space_two_six_comma_space_one_nine_seven_three, w);
        april_space_one_three_comma_space_one_nine_seven_four = loadAndScale(res, R.drawable.april_space_one_three_comma_space_one_nine_seven_four, w);
        june_space_one_nine_seven_four = loadAndScale(res, R.drawable.june_space_one_nine_seven_four, w);
        february_space_one_three_comma_space_one_nine_seven_six = loadAndScale(res, R.drawable.february_space_one_three_comma_space_one_nine_seven_six, w);
        october_space_two_zero_comma_space_one_nine_seven_six = loadAndScale(res, R.drawable.october_space_two_zero_comma_space_one_nine_seven_six, w);
        january_space_two_three_comma_space_one_nine_seven_seven = loadAndScale(res, R.drawable.january_space_two_three_comma_space_one_nine_seven_seven, w);
        march_space_one_nine_comma_space_one_nine_eight_zero = loadAndScale(res, R.drawable.march_space_one_nine_comma_space_one_nine_eight_zero, w);
        june_space_four_comma_space_one_nine_eight_zero = loadAndScale(res, R.drawable.june_space_four_comma_space_one_nine_eight_zero, w);
        august_space_one_comma_space_one_nine_eight_zero = loadAndScale(res, R.drawable.august_space_one_comma_space_one_nine_eight_zero, w);
        september_space_one_nine_eight_one = loadAndScale(res, R.drawable.september_space_one_nine_eight_one, w);
        january_space_seven_comma_space_one_nine_eight_four = loadAndScale(res, R.drawable.january_space_seven_comma_space_one_nine_eight_four, w);
        july_space_one_comma_space_one_nine_eight_six = loadAndScale(res, R.drawable.july_space_one_comma_space_one_nine_eight_six, w);
        june_space_one_nine_eight_eight = loadAndScale(res, R.drawable.june_space_one_nine_eight_eight, w);
        june_space_one_five_comma_space_one_nine_eight_eight = loadAndScale(res, R.drawable.june_space_one_five_comma_space_one_nine_eight_eight, w);
        september_space_one_nine_nine_one = loadAndScale(res, R.drawable.september_space_one_nine_nine_one, w);
        october_space_five_comma_space_one_nine_nine_two = loadAndScale(res, R.drawable.october_space_five_comma_space_one_nine_nine_two, w);
        november_space_one_nine_nine_four = loadAndScale(res, R.drawable.november_space_one_nine_nine_four, w);
        february_space_one_two_comma_space_one_nine_nine_eight = loadAndScale(res, R.drawable.february_space_one_two_comma_space_one_nine_nine_eight, w);
        january_space_one_one_comma_space_two_zero_zero_one = loadAndScale(res, R.drawable.january_space_one_one_comma_space_two_zero_zero_one, w);
        february_space_eight_comma_space_two_zero_zero_one = loadAndScale(res, R.drawable.february_space_eight_comma_space_two_zero_zero_one, w);
        november_space_three_comma_space_two_zero_zero_one = loadAndScale(res, R.drawable.november_space_three_comma_space_two_zero_zero_one, w);
        november_space_one_five_comma_space_two_zero_zero_two = loadAndScale(res, R.drawable.november_space_one_five_comma_space_two_zero_zero_two, w);
        april_space_two_five_comma_space_two_zero_zero_three = loadAndScale(res, R.drawable.april_space_two_five_comma_space_two_zero_zero_three, w);
        may_space_one_two_comma_space_two_zero_zero_three = loadAndScale(res, R.drawable.may_space_one_two_comma_space_two_zero_zero_three, w);
        may_space_one_six_comma_space_two_zero_zero_three = loadAndScale(res, R.drawable.may_space_one_six_comma_space_two_zero_zero_three, w);
        october_space_two_five_comma_space_two_zero_zero_three = loadAndScale(res, R.drawable.october_space_two_five_comma_space_two_zero_zero_three, w);
        may_space_two_one_comma_space_two_zero_zero_four = loadAndScale(res, R.drawable.may_space_two_one_comma_space_two_zero_zero_four, w);
        june_space_one_nine_comma_space_two_zero_zero_four = loadAndScale(res, R.drawable.june_space_one_nine_comma_space_two_zero_zero_four, w);
        december_space_two_comma_space_two_zero_zero_four = loadAndScale(res, R.drawable.december_space_two_comma_space_two_zero_zero_four, w);
        january_space_two_zero_zero_five = loadAndScale(res, R.drawable.january_space_two_zero_zero_five, w);
        february_space_two_four_comma_space_two_zero_zero_five = loadAndScale(res, R.drawable.february_space_two_four_comma_space_two_zero_zero_five, w);
        april_space_one_two_comma_space_two_zero_zero_five = loadAndScale(res, R.drawable.april_space_one_two_comma_space_two_zero_zero_five, w);
        may_space_two_three_comma_space_two_zero_zero_five = loadAndScale(res, R.drawable.may_space_two_three_comma_space_two_zero_zero_five, w);
        august_space_one_nine_comma_space_two_zero_zero_five = loadAndScale(res, R.drawable.august_space_one_nine_comma_space_two_zero_zero_five, w);
        september_space_two_zero_comma_space_two_zero_zero_five = loadAndScale(res, R.drawable.september_space_two_zero_comma_space_two_zero_zero_five, w);
        october_space_one_six_dash_two_three_comma_space_two_zero_zero_five = loadAndScale(res, R.drawable.october_space_one_six_dash_two_three_comma_space_two_zero_zero_five, w);
        june_space_five_comma_space_two_zero_zero_seven = loadAndScale(res, R.drawable.june_space_five_comma_space_two_zero_zero_seven, w);
        august_space_two_four_comma_space_two_zero_zero_seven = loadAndScale(res, R.drawable.august_space_two_four_comma_space_two_zero_zero_seven, w);
        november_space_seven_comma_space_two_zero_zero_seven = loadAndScale(res, R.drawable.november_space_seven_comma_space_two_zero_zero_seven, w);
        april_space_one_zero_comma_space_two_zero_zero_eight = loadAndScale(res, R.drawable.april_space_one_zero_comma_space_two_zero_zero_eight, w);
        november_space_six_comma_space_two_zero_zero_eight = loadAndScale(res, R.drawable.november_space_six_comma_space_two_zero_zero_eight, w);
        december_space_one_seven_comma_space_two_zero_zero_eight = loadAndScale(res, R.drawable.december_space_one_seven_comma_space_two_zero_zero_eight, w);
        january_space_two_five_comma_space_two_zero_zero_nine = loadAndScale(res, R.drawable.january_space_two_five_comma_space_two_zero_zero_nine, w);
        march_space_one_one_comma_space_two_zero_zero_nine = loadAndScale(res, R.drawable.march_space_one_one_comma_space_two_zero_zero_nine, w);
        april_space_four_comma_space_two_zero_zero_nine = loadAndScale(res, R.drawable.april_space_four_comma_space_two_zero_zero_nine, w);
        april_space_two_eight_comma_space_two_zero_zero_nine = loadAndScale(res, R.drawable.april_space_two_eight_comma_space_two_zero_zero_nine, w);
        may_space_one_two_comma_space_two_zero_zero_nine = loadAndScale(res, R.drawable.may_space_one_two_comma_space_two_zero_zero_nine, w);
        july_space_two_seven_comma_space_two_zero_zero_nine = loadAndScale(res, R.drawable.july_space_two_seven_comma_space_two_zero_zero_nine, w);
        july_space_two_seven_comma_space_two_zero_zero_nine_duplicate_zero = loadAndScale(res, R.drawable.july_space_two_seven_comma_space_two_zero_zero_nine_duplicate_zero, w);
        september_space_one_seven_comma_space_two_zero_zero_nine = loadAndScale(res, R.drawable.september_space_one_seven_comma_space_two_zero_zero_nine, w);
        october_space_two_zero_zero_nine = loadAndScale(res, R.drawable.october_space_two_zero_zero_nine, w);
        november_space_five_comma_space_two_zero_zero_nine = loadAndScale(res, R.drawable.november_space_five_comma_space_two_zero_zero_nine, w);
        november_space_two_two_comma_space_two_zero_zero_nine = loadAndScale(res, R.drawable.november_space_two_two_comma_space_two_zero_zero_nine, w);
        january_space_six_comma_space_two_zero_one_zero = loadAndScale(res, R.drawable.january_space_six_comma_space_two_zero_one_zero, w);
        may_space_two_comma_space_two_zero_one_zero = loadAndScale(res, R.drawable.may_space_two_comma_space_two_zero_one_zero, w);
        may_space_two_zero_one_zero = loadAndScale(res, R.drawable.may_space_two_zero_one_zero, w);
        july_space_two_six_comma_space_two_zero_one_zero = loadAndScale(res, R.drawable.july_space_two_six_comma_space_two_zero_one_zero, w);
        november_space_two_one_comma_space_two_zero_one_zero = loadAndScale(res, R.drawable.november_space_two_one_comma_space_two_zero_one_zero, w);
        march_space_one_nine_comma_space_two_zero_one_one = loadAndScale(res, R.drawable.march_space_one_nine_comma_space_two_zero_one_one, w);
        march_space_two_zero_one_one = loadAndScale(res, R.drawable.march_space_two_zero_one_one, w);
        march_space_two_six_comma_space_two_zero_one_one = loadAndScale(res, R.drawable.march_space_two_six_comma_space_two_zero_one_one, w);
        april_space_two_zero_one_one = loadAndScale(res, R.drawable.april_space_two_zero_one_one, w);
        april_space_two_six_comma_space_two_zero_one_one = loadAndScale(res, R.drawable.april_space_two_six_comma_space_two_zero_one_one, w);
        june_space_two_comma_space_two_zero_one_one = loadAndScale(res, R.drawable.june_space_two_comma_space_two_zero_one_one, w);
        september_space_two_zero_one_one = loadAndScale(res, R.drawable.september_space_two_zero_one_one, w);
        september_space_two_two_comma_space_two_zero_one_one = loadAndScale(res, R.drawable.september_space_two_two_comma_space_two_zero_one_one, w);
        november_space_one_zero_comma_space_two_zero_one_one = loadAndScale(res, R.drawable.november_space_one_zero_comma_space_two_zero_one_one, w);
        november_space_one_four_comma_space_two_zero_one_one = loadAndScale(res, R.drawable.november_space_one_four_comma_space_two_zero_one_one, w);
        december_space_nine_comma_space_two_zero_one_one = loadAndScale(res, R.drawable.december_space_nine_comma_space_two_zero_one_one, w);
        december_space_one_seven_comma_space_two_zero_one_one = loadAndScale(res, R.drawable.december_space_one_seven_comma_space_two_zero_one_one, w);
        december_space_two_zero_one_one = loadAndScale(res, R.drawable.december_space_two_zero_one_one, w);
        january_space_two_zero_one_two = loadAndScale(res, R.drawable.january_space_two_zero_one_two, w);
        march_space_eight_dash_one_one_comma_space_two_zero_one_two = loadAndScale(res, R.drawable.march_space_eight_dash_one_one_comma_space_two_zero_one_two, w);
        march_space_nine_comma_space_two_zero_one_two = loadAndScale(res, R.drawable.march_space_nine_comma_space_two_zero_one_two, w);
        april_space_one_six_comma_space_two_zero_one_two = loadAndScale(res, R.drawable.april_space_one_six_comma_space_two_zero_one_two, w);
        april_space_two_three_comma_space_two_zero_one_two = loadAndScale(res, R.drawable.april_space_two_three_comma_space_two_zero_one_two, w);
        may_space_one_eight_comma_space_two_zero_one_two = loadAndScale(res, R.drawable.may_space_one_eight_comma_space_two_zero_one_two, w);
        may_space_one_nine_comma_space_two_zero_one_two = loadAndScale(res, R.drawable.may_space_one_nine_comma_space_two_zero_one_two, w);
        may_space_two_four_comma_space_two_zero_one_two = loadAndScale(res, R.drawable.may_space_two_four_comma_space_two_zero_one_two, w);
        september_space_one_seven_comma_space_two_zero_one_two = loadAndScale(res, R.drawable.september_space_one_seven_comma_space_two_zero_one_two, w);
        september_space_two_six_comma_space_two_zero_one_two = loadAndScale(res, R.drawable.september_space_two_six_comma_space_two_zero_one_two, w);
        october_space_four_comma_space_two_zero_one_two = loadAndScale(res, R.drawable.october_space_four_comma_space_two_zero_one_two, w);
        october_space_one_eight_comma_space_two_zero_one_two = loadAndScale(res, R.drawable.october_space_one_eight_comma_space_two_zero_one_two, w);
        november_space_two_nine_dash_december_space_one_comma_space_two_zero_one_two = loadAndScale(res, R.drawable.november_space_two_nine_dash_december_space_one_comma_space_two_zero_one_two, w);
        january_space_two_zero_one_three = loadAndScale(res, R.drawable.january_space_two_zero_one_three, w);
        may_space_two_zero_one_three = loadAndScale(res, R.drawable.may_space_two_zero_one_three, w);
        may_space_two_two_comma_space_two_zero_one_three = loadAndScale(res, R.drawable.may_space_two_two_comma_space_two_zero_one_three, w);
        june_space_one_zero_dash_two_four_comma_space_two_zero_one_three = loadAndScale(res, R.drawable.june_space_one_zero_dash_two_four_comma_space_two_zero_one_three, w);
        june_dash_august_space_two_zero_one_three = loadAndScale(res, R.drawable.june_dash_august_space_two_zero_one_three, w);
        september_space_eight_comma_space_two_zero_one_three = loadAndScale(res, R.drawable.september_space_eight_comma_space_two_zero_one_three, w);
        october_space_two_zero_one_three = loadAndScale(res, R.drawable.october_space_two_zero_one_three, w);
        october_space_one_one_comma_space_two_zero_one_three = loadAndScale(res, R.drawable.october_space_one_one_comma_space_two_zero_one_three, w);
        october_space_one_one_comma_space_two_zero_one_three_duplicate_one = loadAndScale(res, R.drawable.october_space_one_one_comma_space_two_zero_one_three_duplicate_one, w);
        december_space_one_three_comma_space_two_zero_one_three = loadAndScale(res, R.drawable.december_space_one_three_comma_space_two_zero_one_three, w);
        february_space_nine_comma_space_two_zero_one_four = loadAndScale(res, R.drawable.february_space_nine_comma_space_two_zero_one_four, w);
        march_space_one_two_dash_one_six_comma_space_two_zero_one_four = loadAndScale(res, R.drawable.march_space_one_two_dash_one_six_comma_space_two_zero_one_four, w);
        march_space_two_eight_comma_space_two_zero_one_four = loadAndScale(res, R.drawable.march_space_two_eight_comma_space_two_zero_one_four, w);
        may_space_two_zero_comma_space_two_zero_one_four = loadAndScale(res, R.drawable.may_space_two_zero_comma_space_two_zero_one_four, w);
        september_space_two_zero_one_four = loadAndScale(res, R.drawable.september_space_two_zero_one_four, w);
        september_space_two_zero_one_four_duplicate_two = loadAndScale(res, R.drawable.september_space_two_zero_one_four_duplicate_two, w);
        september_space_two_zero_one_four_duplicate_three = loadAndScale(res, R.drawable.september_space_two_zero_one_four_duplicate_three, w);
        february_space_six_dash_one_two_comma_space_two_zero_one_five = loadAndScale(res, R.drawable.february_space_six_dash_one_two_comma_space_two_zero_one_five, w);
        march_space_one_one_comma_space_two_zero_one_five = loadAndScale(res, R.drawable.march_space_one_one_comma_space_two_zero_one_five, w);
        april_space_one_six_comma_space_two_zero_one_five = loadAndScale(res, R.drawable.april_space_one_six_comma_space_two_zero_one_five, w);
        may_space_one_two_comma_space_two_zero_one_five = loadAndScale(res, R.drawable.may_space_one_two_comma_space_two_zero_one_five, w);
        may_space_two_zero_one_five = loadAndScale(res, R.drawable.may_space_two_zero_one_five, w);
        october_space_two_four_comma_space_two_zero_one_five = loadAndScale(res, R.drawable.october_space_two_four_comma_space_two_zero_one_five, w);
        october_comma_space_two_zero_one_five = loadAndScale(res, R.drawable.october_comma_space_two_zero_one_five, w);
        november_space_one_zero_comma_space_two_zero_one_five = loadAndScale(res, R.drawable.november_space_one_zero_comma_space_two_zero_one_five, w);

        // repeat last step too load all bitmaps
    }

    private static Bitmap loadAndScale(Resources res, int id, float newWidth) {
        Bitmap original = BitmapFactory.decodeResource(res, id);
        float aspectRatio = (float)original.getHeight()/(float)original.getWidth();
        float newHeight = newWidth * aspectRatio;
        return Bitmap.createScaledBitmap(original, (int)newWidth, (int)newHeight, true);
    }

    public static ArrayList<Member> getTempleObjectsList() {

        ArrayList<Member> allObjectsList = new ArrayList<>();

//        for (int i = 0; i <= 144; i ++) {
//            allObjectsList.add(new Member(empty, 0f, 0f, 0f));
//            // repeat this step to create objects with all resized bitmaps
//        }

        allObjectsList.add(new Member(april_space_six_comma_space_one_eight_three_zero, 0f, 0f, 0f));
        allObjectsList.add(new Member(may_space_one_one_comma_space_one_eight_four_three, 0f, 0f, 0f));
        allObjectsList.add(new Member(may_space_one_comma_space_one_eight_four_four, 0f, 0f, 0f));
        allObjectsList.add(new Member(september_space_two_five_comma_space_one_eight_five_zero, 0f, 0f, 0f));
        allObjectsList.add(new Member(december_space_one_two_comma_space_one_eight_five_zero, 0f, 0f, 0f));
        allObjectsList.add(new Member(january_space_two_six_comma_space_one_eight_six_five, 0f, 0f, 0f));
        allObjectsList.add(new Member(october_space_one_eight_six_five, 0f, 0f, 0f));
        allObjectsList.add(new Member(october_space_one_six_comma_space_one_eight_seven_five, 0f, 0f, 0f));
        allObjectsList.add(new Member(june_space_one_comma_space_one_nine_one_five, 0f, 0f, 0f));
        allObjectsList.add(new Member(november_space_two_seven_comma_space_one_nine_one_nine, 0f, 0f, 0f));
        allObjectsList.add(new Member(february_space_seven_comma_space_one_nine_two_one, 0f, 0f, 0f));
        allObjectsList.add(new Member(april_space_nine_comma_space_one_nine_five_one, 0f, 0f, 0f));
        allObjectsList.add(new Member(july_space_two_one_comma_space_one_nine_five_four, 0f, 0f, 0f));
        allObjectsList.add(new Member(february_space_one_two_comma_space_one_nine_five_five, 0f, 0f, 0f));
        allObjectsList.add(new Member(september_space_one_comma_space_one_nine_five_five, 0f, 0f, 0f));
        allObjectsList.add(new Member(september_space_two_six_comma_space_one_nine_five_five, 0f, 0f, 0f));
        allObjectsList.add(new Member(december_space_one_nine_five_five, 0f, 0f, 0f));
        allObjectsList.add(new Member(january_space_one_nine_five_six, 0f, 0f, 0f));
        allObjectsList.add(new Member(june_space_one_comma_space_one_nine_five_six, 0f, 0f, 0f));
        allObjectsList.add(new Member(december_space_one_seven_comma_space_one_nine_five_eight, 0f, 0f, 0f));
        allObjectsList.add(new Member(march_space_one_nine_five_nine, 0f, 0f, 0f));
        allObjectsList.add(new Member(august_space_two_one_comma_space_one_nine_five_nine, 0f, 0f, 0f));
        allObjectsList.add(new Member(august_space_one_nine_five_nine, 0f, 0f, 0f));
        allObjectsList.add(new Member(january_space_one_nine_six_zero, 0f, 0f, 0f));
        allObjectsList.add(new Member(march_space_one_nine_six_zero, 0f, 0f, 0f));
        allObjectsList.add(new Member(february_space_two_three_comma_space_one_nine_six_one, 0f, 0f, 0f));
        allObjectsList.add(new Member(june_space_three_comma_space_one_nine_six_one, 0f, 0f, 0f));
        allObjectsList.add(new Member(early_space_one_nine_six_two, 0f, 0f, 0f));
        allObjectsList.add(new Member(february_space_one_nine_comma_space_one_nine_six_three, 0f, 0f, 0f));
        allObjectsList.add(new Member(october_space_one_two_comma_space_one_nine_six_three, 0f, 0f, 0f));
        allObjectsList.add(new Member(august_space_two_comma_space_one_nine_six_four, 0f, 0f, 0f));
        allObjectsList.add(new Member(october_space_one_nine_six_four, 0f, 0f, 0f));
        allObjectsList.add(new Member(january_space_one_nine_six_eight, 0f, 0f, 0f));
        allObjectsList.add(new Member(february_space_one_seven_comma_space_one_nine_six_nine, 0f, 0f, 0f));
        allObjectsList.add(new Member(may_space_one_five_comma_space_one_nine_six_nine, 0f, 0f, 0f));
        allObjectsList.add(new Member(february_space_one_one_comma_space_one_nine_seven_two, 0f, 0f, 0f));
        allObjectsList.add(new Member(january_space_two_six_comma_space_one_nine_seven_three, 0f, 0f, 0f));
        allObjectsList.add(new Member(april_space_one_three_comma_space_one_nine_seven_four, 0f, 0f, 0f));
        allObjectsList.add(new Member(june_space_one_nine_seven_four, 0f, 0f, 0f));
        allObjectsList.add(new Member(february_space_one_three_comma_space_one_nine_seven_six, 0f, 0f, 0f));
        allObjectsList.add(new Member(october_space_two_zero_comma_space_one_nine_seven_six, 0f, 0f, 0f));
        allObjectsList.add(new Member(january_space_two_three_comma_space_one_nine_seven_seven, 0f, 0f, 0f));
        allObjectsList.add(new Member(march_space_one_nine_comma_space_one_nine_eight_zero, 0f, 0f, 0f));
        allObjectsList.add(new Member(june_space_four_comma_space_one_nine_eight_zero, 0f, 0f, 0f));
        allObjectsList.add(new Member(august_space_one_comma_space_one_nine_eight_zero, 0f, 0f, 0f));
        allObjectsList.add(new Member(september_space_one_nine_eight_one, 0f, 0f, 0f));
        allObjectsList.add(new Member(january_space_seven_comma_space_one_nine_eight_four, 0f, 0f, 0f));
        allObjectsList.add(new Member(july_space_one_comma_space_one_nine_eight_six, 0f, 0f, 0f));
        allObjectsList.add(new Member(june_space_one_nine_eight_eight, 0f, 0f, 0f));
        allObjectsList.add(new Member(june_space_one_five_comma_space_one_nine_eight_eight, 0f, 0f, 0f));
        allObjectsList.add(new Member(september_space_one_nine_nine_one, 0f, 0f, 0f));
        allObjectsList.add(new Member(october_space_five_comma_space_one_nine_nine_two, 0f, 0f, 0f));
        allObjectsList.add(new Member(november_space_one_nine_nine_four, 0f, 0f, 0f));
        allObjectsList.add(new Member(february_space_one_two_comma_space_one_nine_nine_eight, 0f, 0f, 0f));
        allObjectsList.add(new Member(january_space_one_one_comma_space_two_zero_zero_one, 0f, 0f, 0f));
        allObjectsList.add(new Member(february_space_eight_comma_space_two_zero_zero_one, 0f, 0f, 0f));
        allObjectsList.add(new Member(november_space_three_comma_space_two_zero_zero_one, 0f, 0f, 0f));
        allObjectsList.add(new Member(november_space_one_five_comma_space_two_zero_zero_two, 0f, 0f, 0f));
        allObjectsList.add(new Member(april_space_two_five_comma_space_two_zero_zero_three, 0f, 0f, 0f));
        allObjectsList.add(new Member(may_space_one_two_comma_space_two_zero_zero_three, 0f, 0f, 0f));
        allObjectsList.add(new Member(may_space_one_six_comma_space_two_zero_zero_three, 0f, 0f, 0f));
        allObjectsList.add(new Member(october_space_two_five_comma_space_two_zero_zero_three, 0f, 0f, 0f));
        allObjectsList.add(new Member(may_space_two_one_comma_space_two_zero_zero_four, 0f, 0f, 0f));
        allObjectsList.add(new Member(june_space_one_nine_comma_space_two_zero_zero_four, 0f, 0f, 0f));
        allObjectsList.add(new Member(december_space_two_comma_space_two_zero_zero_four, 0f, 0f, 0f));
        allObjectsList.add(new Member(january_space_two_zero_zero_five, 0f, 0f, 0f));
        allObjectsList.add(new Member(february_space_two_four_comma_space_two_zero_zero_five, 0f, 0f, 0f));
        allObjectsList.add(new Member(april_space_one_two_comma_space_two_zero_zero_five, 0f, 0f, 0f));
        allObjectsList.add(new Member(may_space_two_three_comma_space_two_zero_zero_five, 0f, 0f, 0f));
        allObjectsList.add(new Member(august_space_one_nine_comma_space_two_zero_zero_five, 0f, 0f, 0f));
        allObjectsList.add(new Member(september_space_two_zero_comma_space_two_zero_zero_five, 0f, 0f, 0f));
        allObjectsList.add(new Member(october_space_one_six_dash_two_three_comma_space_two_zero_zero_five, 0f, 0f, 0f));
        allObjectsList.add(new Member(june_space_five_comma_space_two_zero_zero_seven, 0f, 0f, 0f));
        allObjectsList.add(new Member(august_space_two_four_comma_space_two_zero_zero_seven, 0f, 0f, 0f));
        allObjectsList.add(new Member(november_space_seven_comma_space_two_zero_zero_seven, 0f, 0f, 0f));
        allObjectsList.add(new Member(april_space_one_zero_comma_space_two_zero_zero_eight, 0f, 0f, 0f));
        allObjectsList.add(new Member(november_space_six_comma_space_two_zero_zero_eight, 0f, 0f, 0f));
        allObjectsList.add(new Member(december_space_one_seven_comma_space_two_zero_zero_eight, 0f, 0f, 0f));
        allObjectsList.add(new Member(january_space_two_five_comma_space_two_zero_zero_nine, 0f, 0f, 0f));
        allObjectsList.add(new Member(march_space_one_one_comma_space_two_zero_zero_nine, 0f, 0f, 0f));
        allObjectsList.add(new Member(april_space_four_comma_space_two_zero_zero_nine, 0f, 0f, 0f));
        allObjectsList.add(new Member(april_space_two_eight_comma_space_two_zero_zero_nine, 0f, 0f, 0f));
        allObjectsList.add(new Member(may_space_one_two_comma_space_two_zero_zero_nine, 0f, 0f, 0f));
        allObjectsList.add(new Member(july_space_two_seven_comma_space_two_zero_zero_nine, 0f, 0f, 0f));
        allObjectsList.add(new Member(july_space_two_seven_comma_space_two_zero_zero_nine_duplicate_zero, 0f, 0f, 0f));
        allObjectsList.add(new Member(september_space_one_seven_comma_space_two_zero_zero_nine, 0f, 0f, 0f));
        allObjectsList.add(new Member(october_space_two_zero_zero_nine, 0f, 0f, 0f));
        allObjectsList.add(new Member(november_space_five_comma_space_two_zero_zero_nine, 0f, 0f, 0f));
        allObjectsList.add(new Member(november_space_two_two_comma_space_two_zero_zero_nine, 0f, 0f, 0f));
        allObjectsList.add(new Member(january_space_six_comma_space_two_zero_one_zero, 0f, 0f, 0f));
        allObjectsList.add(new Member(may_space_two_comma_space_two_zero_one_zero, 0f, 0f, 0f));
        allObjectsList.add(new Member(may_space_two_zero_one_zero, 0f, 0f, 0f));
        allObjectsList.add(new Member(july_space_two_six_comma_space_two_zero_one_zero, 0f, 0f, 0f));
        allObjectsList.add(new Member(november_space_two_one_comma_space_two_zero_one_zero, 0f, 0f, 0f));
        allObjectsList.add(new Member(march_space_one_nine_comma_space_two_zero_one_one, 0f, 0f, 0f));
        allObjectsList.add(new Member(march_space_two_zero_one_one, 0f, 0f, 0f));
        allObjectsList.add(new Member(march_space_two_six_comma_space_two_zero_one_one, 0f, 0f, 0f));
        allObjectsList.add(new Member(april_space_two_zero_one_one, 0f, 0f, 0f));
        allObjectsList.add(new Member(april_space_two_six_comma_space_two_zero_one_one, 0f, 0f, 0f));
        allObjectsList.add(new Member(june_space_two_comma_space_two_zero_one_one, 0f, 0f, 0f));
        allObjectsList.add(new Member(september_space_two_zero_one_one, 0f, 0f, 0f));
        allObjectsList.add(new Member(september_space_two_two_comma_space_two_zero_one_one, 0f, 0f, 0f));
        allObjectsList.add(new Member(november_space_one_zero_comma_space_two_zero_one_one, 0f, 0f, 0f));
        allObjectsList.add(new Member(november_space_one_four_comma_space_two_zero_one_one, 0f, 0f, 0f));
        allObjectsList.add(new Member(december_space_nine_comma_space_two_zero_one_one, 0f, 0f, 0f));
        allObjectsList.add(new Member(december_space_one_seven_comma_space_two_zero_one_one, 0f, 0f, 0f));
        allObjectsList.add(new Member(december_space_two_zero_one_one, 0f, 0f, 0f));
        allObjectsList.add(new Member(january_space_two_zero_one_two, 0f, 0f, 0f));
        allObjectsList.add(new Member(march_space_eight_dash_one_one_comma_space_two_zero_one_two, 0f, 0f, 0f));
        allObjectsList.add(new Member(march_space_nine_comma_space_two_zero_one_two, 0f, 0f, 0f));
        allObjectsList.add(new Member(april_space_one_six_comma_space_two_zero_one_two, 0f, 0f, 0f));
        allObjectsList.add(new Member(april_space_two_three_comma_space_two_zero_one_two, 0f, 0f, 0f));
        allObjectsList.add(new Member(may_space_one_eight_comma_space_two_zero_one_two, 0f, 0f, 0f));
        allObjectsList.add(new Member(may_space_one_nine_comma_space_two_zero_one_two, 0f, 0f, 0f));
        allObjectsList.add(new Member(may_space_two_four_comma_space_two_zero_one_two, 0f, 0f, 0f));
        allObjectsList.add(new Member(september_space_one_seven_comma_space_two_zero_one_two, 0f, 0f, 0f));
        allObjectsList.add(new Member(september_space_two_six_comma_space_two_zero_one_two, 0f, 0f, 0f));
        allObjectsList.add(new Member(october_space_four_comma_space_two_zero_one_two, 0f, 0f, 0f));
        allObjectsList.add(new Member(october_space_one_eight_comma_space_two_zero_one_two, 0f, 0f, 0f));
        allObjectsList.add(new Member(november_space_two_nine_dash_december_space_one_comma_space_two_zero_one_two, 0f, 0f, 0f));
        allObjectsList.add(new Member(january_space_two_zero_one_three, 0f, 0f, 0f));
        allObjectsList.add(new Member(may_space_two_zero_one_three, 0f, 0f, 0f));
        allObjectsList.add(new Member(may_space_two_two_comma_space_two_zero_one_three, 0f, 0f, 0f));
        allObjectsList.add(new Member(june_space_one_zero_dash_two_four_comma_space_two_zero_one_three, 0f, 0f, 0f));
        allObjectsList.add(new Member(june_dash_august_space_two_zero_one_three, 0f, 0f, 0f));
        allObjectsList.add(new Member(september_space_eight_comma_space_two_zero_one_three, 0f, 0f, 0f));
        allObjectsList.add(new Member(october_space_two_zero_one_three, 0f, 0f, 0f));
        allObjectsList.add(new Member(october_space_one_one_comma_space_two_zero_one_three, 0f, 0f, 0f));
        allObjectsList.add(new Member(october_space_one_one_comma_space_two_zero_one_three_duplicate_one, 0f, 0f, 0f));
        allObjectsList.add(new Member(december_space_one_three_comma_space_two_zero_one_three, 0f, 0f, 0f));
        allObjectsList.add(new Member(february_space_nine_comma_space_two_zero_one_four, 0f, 0f, 0f));
        allObjectsList.add(new Member(march_space_one_two_dash_one_six_comma_space_two_zero_one_four, 0f, 0f, 0f));
        allObjectsList.add(new Member(march_space_two_eight_comma_space_two_zero_one_four, 0f, 0f, 0f));
        allObjectsList.add(new Member(may_space_two_zero_comma_space_two_zero_one_four, 0f, 0f, 0f));
        allObjectsList.add(new Member(september_space_two_zero_one_four, 0f, 0f, 0f));
        allObjectsList.add(new Member(september_space_two_zero_one_four_duplicate_two, 0f, 0f, 0f));
        allObjectsList.add(new Member(september_space_two_zero_one_four_duplicate_three, 0f, 0f, 0f));
        allObjectsList.add(new Member(february_space_six_dash_one_two_comma_space_two_zero_one_five, 0f, 0f, 0f));
        allObjectsList.add(new Member(march_space_one_one_comma_space_two_zero_one_five, 0f, 0f, 0f));
        allObjectsList.add(new Member(april_space_one_six_comma_space_two_zero_one_five, 0f, 0f, 0f));
        allObjectsList.add(new Member(may_space_one_two_comma_space_two_zero_one_five, 0f, 0f, 0f));
        allObjectsList.add(new Member(may_space_two_zero_one_five, 0f, 0f, 0f));
        allObjectsList.add(new Member(october_space_two_four_comma_space_two_zero_one_five, 0f, 0f, 0f));
        allObjectsList.add(new Member(october_comma_space_two_zero_one_five, 0f, 0f, 0f));
        allObjectsList.add(new Member(november_space_one_zero_comma_space_two_zero_one_five, 0f, 0f, 0f));

        return allObjectsList;
    }

    public static ArrayList<Integer> getAllLargeImagesIds() {

        ArrayList<Integer> allLargeImagesIds = new ArrayList<>();

//        for (int i = 0; i <= 144; i ++) {
//            allLargeImagesIds.add(R.drawable.example_large);
//            // repeat this step to add all large images' id to a list
//        }

        allLargeImagesIds.add(R.drawable.april_space_six_comma_space_one_eight_three_zero_large);
        allLargeImagesIds.add(R.drawable.may_space_one_one_comma_space_one_eight_four_three_large);
        allLargeImagesIds.add(R.drawable.may_space_one_comma_space_one_eight_four_four_large);
        allLargeImagesIds.add(R.drawable.september_space_two_five_comma_space_one_eight_five_zero_large);
        allLargeImagesIds.add(R.drawable.december_space_one_two_comma_space_one_eight_five_zero_large);
        allLargeImagesIds.add(R.drawable.january_space_two_six_comma_space_one_eight_six_five_large);
        allLargeImagesIds.add(R.drawable.october_space_one_eight_six_five_large);
        allLargeImagesIds.add(R.drawable.october_space_one_six_comma_space_one_eight_seven_five_large);
        allLargeImagesIds.add(R.drawable.june_space_one_comma_space_one_nine_one_five_large);
        allLargeImagesIds.add(R.drawable.november_space_two_seven_comma_space_one_nine_one_nine_large);
        allLargeImagesIds.add(R.drawable.february_space_seven_comma_space_one_nine_two_one_large);
        allLargeImagesIds.add(R.drawable.april_space_nine_comma_space_one_nine_five_one_large);
        allLargeImagesIds.add(R.drawable.july_space_two_one_comma_space_one_nine_five_four_large);
        allLargeImagesIds.add(R.drawable.february_space_one_two_comma_space_one_nine_five_five_large);
        allLargeImagesIds.add(R.drawable.september_space_one_comma_space_one_nine_five_five_large);
        allLargeImagesIds.add(R.drawable.september_space_two_six_comma_space_one_nine_five_five_large);
        allLargeImagesIds.add(R.drawable.december_space_one_nine_five_five_large);
        allLargeImagesIds.add(R.drawable.january_space_one_nine_five_six_large);
        allLargeImagesIds.add(R.drawable.june_space_one_comma_space_one_nine_five_six_large);
        allLargeImagesIds.add(R.drawable.december_space_one_seven_comma_space_one_nine_five_eight_large);
        allLargeImagesIds.add(R.drawable.march_space_one_nine_five_nine_large);
        allLargeImagesIds.add(R.drawable.august_space_two_one_comma_space_one_nine_five_nine_large);
        allLargeImagesIds.add(R.drawable.august_space_one_nine_five_nine_large);
        allLargeImagesIds.add(R.drawable.january_space_one_nine_six_zero_large);
        allLargeImagesIds.add(R.drawable.march_space_one_nine_six_zero_large);
        allLargeImagesIds.add(R.drawable.february_space_two_three_comma_space_one_nine_six_one_large);
        allLargeImagesIds.add(R.drawable.june_space_three_comma_space_one_nine_six_one_large);
        allLargeImagesIds.add(R.drawable.early_space_one_nine_six_two_large);
        allLargeImagesIds.add(R.drawable.february_space_one_nine_comma_space_one_nine_six_three_large);
        allLargeImagesIds.add(R.drawable.october_space_one_two_comma_space_one_nine_six_three_large);
        allLargeImagesIds.add(R.drawable.august_space_two_comma_space_one_nine_six_four_large);
        allLargeImagesIds.add(R.drawable.october_space_one_nine_six_four_large);
        allLargeImagesIds.add(R.drawable.january_space_one_nine_six_eight_large);
        allLargeImagesIds.add(R.drawable.february_space_one_seven_comma_space_one_nine_six_nine_large);
        allLargeImagesIds.add(R.drawable.may_space_one_five_comma_space_one_nine_six_nine_large);
        allLargeImagesIds.add(R.drawable.february_space_one_one_comma_space_one_nine_seven_two_large);
        allLargeImagesIds.add(R.drawable.january_space_two_six_comma_space_one_nine_seven_three_large);
        allLargeImagesIds.add(R.drawable.april_space_one_three_comma_space_one_nine_seven_four_large);
        allLargeImagesIds.add(R.drawable.june_space_one_nine_seven_four_large);
        allLargeImagesIds.add(R.drawable.february_space_one_three_comma_space_one_nine_seven_six_large);
        allLargeImagesIds.add(R.drawable.october_space_two_zero_comma_space_one_nine_seven_six_large);
        allLargeImagesIds.add(R.drawable.january_space_two_three_comma_space_one_nine_seven_seven_large);
        allLargeImagesIds.add(R.drawable.march_space_one_nine_comma_space_one_nine_eight_zero_large);
        allLargeImagesIds.add(R.drawable.june_space_four_comma_space_one_nine_eight_zero_large);
        allLargeImagesIds.add(R.drawable.august_space_one_comma_space_one_nine_eight_zero_large);
        allLargeImagesIds.add(R.drawable.september_space_one_nine_eight_one_large);
        allLargeImagesIds.add(R.drawable.january_space_seven_comma_space_one_nine_eight_four_large);
        allLargeImagesIds.add(R.drawable.july_space_one_comma_space_one_nine_eight_six_large);
        allLargeImagesIds.add(R.drawable.june_space_one_nine_eight_eight_large);
        allLargeImagesIds.add(R.drawable.june_space_one_five_comma_space_one_nine_eight_eight_large);
        allLargeImagesIds.add(R.drawable.september_space_one_nine_nine_one_large);
        allLargeImagesIds.add(R.drawable.october_space_five_comma_space_one_nine_nine_two_large);
        allLargeImagesIds.add(R.drawable.november_space_one_nine_nine_four_large);
        allLargeImagesIds.add(R.drawable.february_space_one_two_comma_space_one_nine_nine_eight_large);
        allLargeImagesIds.add(R.drawable.january_space_one_one_comma_space_two_zero_zero_one_large);
        allLargeImagesIds.add(R.drawable.february_space_eight_comma_space_two_zero_zero_one_large);
        allLargeImagesIds.add(R.drawable.november_space_three_comma_space_two_zero_zero_one_large);
        allLargeImagesIds.add(R.drawable.november_space_one_five_comma_space_two_zero_zero_two_large);
        allLargeImagesIds.add(R.drawable.april_space_two_five_comma_space_two_zero_zero_three_large);
        allLargeImagesIds.add(R.drawable.may_space_one_two_comma_space_two_zero_zero_three_large);
        allLargeImagesIds.add(R.drawable.may_space_one_six_comma_space_two_zero_zero_three_large);
        allLargeImagesIds.add(R.drawable.october_space_two_five_comma_space_two_zero_zero_three_large);
        allLargeImagesIds.add(R.drawable.may_space_two_one_comma_space_two_zero_zero_four_large);
        allLargeImagesIds.add(R.drawable.june_space_one_nine_comma_space_two_zero_zero_four_large);
        allLargeImagesIds.add(R.drawable.december_space_two_comma_space_two_zero_zero_four_large);
        allLargeImagesIds.add(R.drawable.january_space_two_zero_zero_five_large);
        allLargeImagesIds.add(R.drawable.february_space_two_four_comma_space_two_zero_zero_five_large);
        allLargeImagesIds.add(R.drawable.april_space_one_two_comma_space_two_zero_zero_five_large);
        allLargeImagesIds.add(R.drawable.may_space_two_three_comma_space_two_zero_zero_five_large);
        allLargeImagesIds.add(R.drawable.august_space_one_nine_comma_space_two_zero_zero_five_large);
        allLargeImagesIds.add(R.drawable.september_space_two_zero_comma_space_two_zero_zero_five_large);
        allLargeImagesIds.add(R.drawable.october_space_one_six_dash_two_three_comma_space_two_zero_zero_five_large);
        allLargeImagesIds.add(R.drawable.june_space_five_comma_space_two_zero_zero_seven_large);
        allLargeImagesIds.add(R.drawable.august_space_two_four_comma_space_two_zero_zero_seven_large);
        allLargeImagesIds.add(R.drawable.november_space_seven_comma_space_two_zero_zero_seven_large);
        allLargeImagesIds.add(R.drawable.april_space_one_zero_comma_space_two_zero_zero_eight_large);
        allLargeImagesIds.add(R.drawable.november_space_six_comma_space_two_zero_zero_eight_large);
        allLargeImagesIds.add(R.drawable.december_space_one_seven_comma_space_two_zero_zero_eight_large);
        allLargeImagesIds.add(R.drawable.january_space_two_five_comma_space_two_zero_zero_nine_large);
        allLargeImagesIds.add(R.drawable.march_space_one_one_comma_space_two_zero_zero_nine_large);
        allLargeImagesIds.add(R.drawable.april_space_four_comma_space_two_zero_zero_nine_large);
        allLargeImagesIds.add(R.drawable.april_space_two_eight_comma_space_two_zero_zero_nine_large);
        allLargeImagesIds.add(R.drawable.may_space_one_two_comma_space_two_zero_zero_nine_large);
        allLargeImagesIds.add(R.drawable.july_space_two_seven_comma_space_two_zero_zero_nine_large);
        allLargeImagesIds.add(R.drawable.july_space_two_seven_comma_space_two_zero_zero_nine_duplicate_zero_large);
        allLargeImagesIds.add(R.drawable.september_space_one_seven_comma_space_two_zero_zero_nine_large);
        allLargeImagesIds.add(R.drawable.october_space_two_zero_zero_nine_large);
        allLargeImagesIds.add(R.drawable.november_space_five_comma_space_two_zero_zero_nine_large);
        allLargeImagesIds.add(R.drawable.november_space_two_two_comma_space_two_zero_zero_nine_large);
        allLargeImagesIds.add(R.drawable.january_space_six_comma_space_two_zero_one_zero_large);
        allLargeImagesIds.add(R.drawable.may_space_two_comma_space_two_zero_one_zero_large);
        allLargeImagesIds.add(R.drawable.may_space_two_zero_one_zero_large);
        allLargeImagesIds.add(R.drawable.july_space_two_six_comma_space_two_zero_one_zero_large);
        allLargeImagesIds.add(R.drawable.november_space_two_one_comma_space_two_zero_one_zero_large);
        allLargeImagesIds.add(R.drawable.march_space_one_nine_comma_space_two_zero_one_one_large);
        allLargeImagesIds.add(R.drawable.march_space_two_zero_one_one_large);
        allLargeImagesIds.add(R.drawable.march_space_two_six_comma_space_two_zero_one_one_large);
        allLargeImagesIds.add(R.drawable.april_space_two_zero_one_one_large);
        allLargeImagesIds.add(R.drawable.april_space_two_six_comma_space_two_zero_one_one_large);
        allLargeImagesIds.add(R.drawable.june_space_two_comma_space_two_zero_one_one_large);
        allLargeImagesIds.add(R.drawable.september_space_two_zero_one_one_large);
        allLargeImagesIds.add(R.drawable.september_space_two_two_comma_space_two_zero_one_one_large);
        allLargeImagesIds.add(R.drawable.november_space_one_zero_comma_space_two_zero_one_one_large);
        allLargeImagesIds.add(R.drawable.november_space_one_four_comma_space_two_zero_one_one_large);
        allLargeImagesIds.add(R.drawable.december_space_nine_comma_space_two_zero_one_one_large);
        allLargeImagesIds.add(R.drawable.december_space_one_seven_comma_space_two_zero_one_one_large);
        allLargeImagesIds.add(R.drawable.december_space_two_zero_one_one_large);
        allLargeImagesIds.add(R.drawable.january_space_two_zero_one_two_large);
        allLargeImagesIds.add(R.drawable.march_space_eight_dash_one_one_comma_space_two_zero_one_two_large);
        allLargeImagesIds.add(R.drawable.march_space_nine_comma_space_two_zero_one_two_large);
        allLargeImagesIds.add(R.drawable.april_space_one_six_comma_space_two_zero_one_two_large);
        allLargeImagesIds.add(R.drawable.april_space_two_three_comma_space_two_zero_one_two_large);
        allLargeImagesIds.add(R.drawable.may_space_one_eight_comma_space_two_zero_one_two_large);
        allLargeImagesIds.add(R.drawable.may_space_one_nine_comma_space_two_zero_one_two_large);
        allLargeImagesIds.add(R.drawable.may_space_two_four_comma_space_two_zero_one_two_large);
        allLargeImagesIds.add(R.drawable.september_space_one_seven_comma_space_two_zero_one_two_large);
        allLargeImagesIds.add(R.drawable.september_space_two_six_comma_space_two_zero_one_two_large);
        allLargeImagesIds.add(R.drawable.october_space_four_comma_space_two_zero_one_two_large);
        allLargeImagesIds.add(R.drawable.october_space_one_eight_comma_space_two_zero_one_two_large);
        allLargeImagesIds.add(R.drawable.november_space_two_nine_dash_december_space_one_comma_space_two_zero_one_two_large);
        allLargeImagesIds.add(R.drawable.january_space_two_zero_one_three_large);
        allLargeImagesIds.add(R.drawable.may_space_two_zero_one_three_large);
        allLargeImagesIds.add(R.drawable.may_space_two_two_comma_space_two_zero_one_three_large);
        allLargeImagesIds.add(R.drawable.june_space_one_zero_dash_two_four_comma_space_two_zero_one_three_large);
        allLargeImagesIds.add(R.drawable.june_dash_august_space_two_zero_one_three_large);
        allLargeImagesIds.add(R.drawable.september_space_eight_comma_space_two_zero_one_three_large);
        allLargeImagesIds.add(R.drawable.october_space_two_zero_one_three_large);
        allLargeImagesIds.add(R.drawable.october_space_one_one_comma_space_two_zero_one_three_large);
        allLargeImagesIds.add(R.drawable.october_space_one_one_comma_space_two_zero_one_three_duplicate_one_large);
        allLargeImagesIds.add(R.drawable.december_space_one_three_comma_space_two_zero_one_three_large);
        allLargeImagesIds.add(R.drawable.february_space_nine_comma_space_two_zero_one_four_large);
        allLargeImagesIds.add(R.drawable.march_space_one_two_dash_one_six_comma_space_two_zero_one_four_large);
        allLargeImagesIds.add(R.drawable.march_space_two_eight_comma_space_two_zero_one_four_large);
        allLargeImagesIds.add(R.drawable.may_space_two_zero_comma_space_two_zero_one_four_large);
        allLargeImagesIds.add(R.drawable.september_space_two_zero_one_four_large);
        allLargeImagesIds.add(R.drawable.september_space_two_zero_one_four_duplicate_two_large);
        allLargeImagesIds.add(R.drawable.september_space_two_zero_one_four_duplicate_three_large);
        allLargeImagesIds.add(R.drawable.february_space_six_dash_one_two_comma_space_two_zero_one_five_large);
        allLargeImagesIds.add(R.drawable.march_space_one_one_comma_space_two_zero_one_five_large);
        allLargeImagesIds.add(R.drawable.april_space_one_six_comma_space_two_zero_one_five_large);
        allLargeImagesIds.add(R.drawable.may_space_one_two_comma_space_two_zero_one_five_large);
        allLargeImagesIds.add(R.drawable.may_space_two_zero_one_five_large);
        allLargeImagesIds.add(R.drawable.october_space_two_four_comma_space_two_zero_one_five_large);
        allLargeImagesIds.add(R.drawable.october_comma_space_two_zero_one_five_large);
        allLargeImagesIds.add(R.drawable.november_space_one_zero_comma_space_two_zero_one_five_large);

        return allLargeImagesIds;
    }

    public static ArrayList<Integer> getAllInfoFilesIds() {

        ArrayList<Integer> allInfoFilesIds = new ArrayList<>();

        allInfoFilesIds.add(R.raw.april_space_six_comma_space_one_eight_three_zero);
        allInfoFilesIds.add(R.raw.may_space_one_one_comma_space_one_eight_four_three);
        allInfoFilesIds.add(R.raw.may_space_one_comma_space_one_eight_four_four);
        allInfoFilesIds.add(R.raw.september_space_two_five_comma_space_one_eight_five_zero);
        allInfoFilesIds.add(R.raw.december_space_one_two_comma_space_one_eight_five_zero);
        allInfoFilesIds.add(R.raw.january_space_two_six_comma_space_one_eight_six_five);
        allInfoFilesIds.add(R.raw.october_space_one_eight_six_five);
        allInfoFilesIds.add(R.raw.october_space_one_six_comma_space_one_eight_seven_five);
        allInfoFilesIds.add(R.raw.june_space_one_comma_space_one_nine_one_five);
        allInfoFilesIds.add(R.raw.november_space_two_seven_comma_space_one_nine_one_nine);
        allInfoFilesIds.add(R.raw.february_space_seven_comma_space_one_nine_two_one);
        allInfoFilesIds.add(R.raw.april_space_nine_comma_space_one_nine_five_one);
        allInfoFilesIds.add(R.raw.july_space_two_one_comma_space_one_nine_five_four);
        allInfoFilesIds.add(R.raw.february_space_one_two_comma_space_one_nine_five_five);
        allInfoFilesIds.add(R.raw.september_space_one_comma_space_one_nine_five_five);
        allInfoFilesIds.add(R.raw.september_space_two_six_comma_space_one_nine_five_five);
        allInfoFilesIds.add(R.raw.december_space_one_nine_five_five);
        allInfoFilesIds.add(R.raw.january_space_one_nine_five_six);
        allInfoFilesIds.add(R.raw.june_space_one_comma_space_one_nine_five_six);
        allInfoFilesIds.add(R.raw.december_space_one_seven_comma_space_one_nine_five_eight);
        allInfoFilesIds.add(R.raw.march_space_one_nine_five_nine);
        allInfoFilesIds.add(R.raw.august_space_two_one_comma_space_one_nine_five_nine);
        allInfoFilesIds.add(R.raw.august_space_one_nine_five_nine);
        allInfoFilesIds.add(R.raw.january_space_one_nine_six_zero);
        allInfoFilesIds.add(R.raw.march_space_one_nine_six_zero);
        allInfoFilesIds.add(R.raw.february_space_two_three_comma_space_one_nine_six_one);
        allInfoFilesIds.add(R.raw.june_space_three_comma_space_one_nine_six_one);
        allInfoFilesIds.add(R.raw.early_space_one_nine_six_two);
        allInfoFilesIds.add(R.raw.february_space_one_nine_comma_space_one_nine_six_three);
        allInfoFilesIds.add(R.raw.october_space_one_two_comma_space_one_nine_six_three);
        allInfoFilesIds.add(R.raw.august_space_two_comma_space_one_nine_six_four);
        allInfoFilesIds.add(R.raw.october_space_one_nine_six_four);
        allInfoFilesIds.add(R.raw.january_space_one_nine_six_eight);
        allInfoFilesIds.add(R.raw.february_space_one_seven_comma_space_one_nine_six_nine);
        allInfoFilesIds.add(R.raw.may_space_one_five_comma_space_one_nine_six_nine);
        allInfoFilesIds.add(R.raw.february_space_one_one_comma_space_one_nine_seven_two);
        allInfoFilesIds.add(R.raw.january_space_two_six_comma_space_one_nine_seven_three);
        allInfoFilesIds.add(R.raw.april_space_one_three_comma_space_one_nine_seven_four);
        allInfoFilesIds.add(R.raw.june_space_one_nine_seven_four);
        allInfoFilesIds.add(R.raw.february_space_one_three_comma_space_one_nine_seven_six);
        allInfoFilesIds.add(R.raw.october_space_two_zero_comma_space_one_nine_seven_six);
        allInfoFilesIds.add(R.raw.january_space_two_three_comma_space_one_nine_seven_seven);
        allInfoFilesIds.add(R.raw.march_space_one_nine_comma_space_one_nine_eight_zero);
        allInfoFilesIds.add(R.raw.june_space_four_comma_space_one_nine_eight_zero);
        allInfoFilesIds.add(R.raw.august_space_one_comma_space_one_nine_eight_zero);
        allInfoFilesIds.add(R.raw.september_space_one_nine_eight_one);
        allInfoFilesIds.add(R.raw.january_space_seven_comma_space_one_nine_eight_four);
        allInfoFilesIds.add(R.raw.july_space_one_comma_space_one_nine_eight_six);
        allInfoFilesIds.add(R.raw.june_space_one_nine_eight_eight);
        allInfoFilesIds.add(R.raw.june_space_one_five_comma_space_one_nine_eight_eight);
        allInfoFilesIds.add(R.raw.september_space_one_nine_nine_one);
        allInfoFilesIds.add(R.raw.october_space_five_comma_space_one_nine_nine_two);
        allInfoFilesIds.add(R.raw.november_space_one_nine_nine_four);
        allInfoFilesIds.add(R.raw.february_space_one_two_comma_space_one_nine_nine_eight);
        allInfoFilesIds.add(R.raw.january_space_one_one_comma_space_two_zero_zero_one);
        allInfoFilesIds.add(R.raw.february_space_eight_comma_space_two_zero_zero_one);
        allInfoFilesIds.add(R.raw.november_space_three_comma_space_two_zero_zero_one);
        allInfoFilesIds.add(R.raw.november_space_one_five_comma_space_two_zero_zero_two);
        allInfoFilesIds.add(R.raw.april_space_two_five_comma_space_two_zero_zero_three);
        allInfoFilesIds.add(R.raw.may_space_one_two_comma_space_two_zero_zero_three);
        allInfoFilesIds.add(R.raw.may_space_one_six_comma_space_two_zero_zero_three);
        allInfoFilesIds.add(R.raw.october_space_two_five_comma_space_two_zero_zero_three);
        allInfoFilesIds.add(R.raw.may_space_two_one_comma_space_two_zero_zero_four);
        allInfoFilesIds.add(R.raw.june_space_one_nine_comma_space_two_zero_zero_four);
        allInfoFilesIds.add(R.raw.december_space_two_comma_space_two_zero_zero_four);
        allInfoFilesIds.add(R.raw.january_space_two_zero_zero_five);
        allInfoFilesIds.add(R.raw.february_space_two_four_comma_space_two_zero_zero_five);
        allInfoFilesIds.add(R.raw.april_space_one_two_comma_space_two_zero_zero_five);
        allInfoFilesIds.add(R.raw.may_space_two_three_comma_space_two_zero_zero_five);
        allInfoFilesIds.add(R.raw.august_space_one_nine_comma_space_two_zero_zero_five);
        allInfoFilesIds.add(R.raw.september_space_two_zero_comma_space_two_zero_zero_five);
        allInfoFilesIds.add(R.raw.october_space_one_six_dash_two_three_comma_space_two_zero_zero_five);
        allInfoFilesIds.add(R.raw.june_space_five_comma_space_two_zero_zero_seven);
        allInfoFilesIds.add(R.raw.august_space_two_four_comma_space_two_zero_zero_seven);
        allInfoFilesIds.add(R.raw.november_space_seven_comma_space_two_zero_zero_seven);
        allInfoFilesIds.add(R.raw.april_space_one_zero_comma_space_two_zero_zero_eight);
        allInfoFilesIds.add(R.raw.november_space_six_comma_space_two_zero_zero_eight);
        allInfoFilesIds.add(R.raw.december_space_one_seven_comma_space_two_zero_zero_eight);
        allInfoFilesIds.add(R.raw.january_space_two_five_comma_space_two_zero_zero_nine);
        allInfoFilesIds.add(R.raw.march_space_one_one_comma_space_two_zero_zero_nine);
        allInfoFilesIds.add(R.raw.april_space_four_comma_space_two_zero_zero_nine);
        allInfoFilesIds.add(R.raw.april_space_two_eight_comma_space_two_zero_zero_nine);
        allInfoFilesIds.add(R.raw.may_space_one_two_comma_space_two_zero_zero_nine);
        allInfoFilesIds.add(R.raw.july_space_two_seven_comma_space_two_zero_zero_nine);
        allInfoFilesIds.add(R.raw.july_space_two_seven_comma_space_two_zero_zero_nine_duplicate_zero);
        allInfoFilesIds.add(R.raw.september_space_one_seven_comma_space_two_zero_zero_nine);
        allInfoFilesIds.add(R.raw.october_space_two_zero_zero_nine);
        allInfoFilesIds.add(R.raw.november_space_five_comma_space_two_zero_zero_nine);
        allInfoFilesIds.add(R.raw.november_space_two_two_comma_space_two_zero_zero_nine);
        allInfoFilesIds.add(R.raw.january_space_six_comma_space_two_zero_one_zero);
        allInfoFilesIds.add(R.raw.may_space_two_comma_space_two_zero_one_zero);
        allInfoFilesIds.add(R.raw.may_space_two_zero_one_zero);
        allInfoFilesIds.add(R.raw.july_space_two_six_comma_space_two_zero_one_zero);
        allInfoFilesIds.add(R.raw.november_space_two_one_comma_space_two_zero_one_zero);
        allInfoFilesIds.add(R.raw.march_space_one_nine_comma_space_two_zero_one_one);
        allInfoFilesIds.add(R.raw.march_space_two_zero_one_one);
        allInfoFilesIds.add(R.raw.march_space_two_six_comma_space_two_zero_one_one);
        allInfoFilesIds.add(R.raw.april_space_two_zero_one_one);
        allInfoFilesIds.add(R.raw.april_space_two_six_comma_space_two_zero_one_one);
        allInfoFilesIds.add(R.raw.june_space_two_comma_space_two_zero_one_one);
        allInfoFilesIds.add(R.raw.september_space_two_zero_one_one);
        allInfoFilesIds.add(R.raw.september_space_two_two_comma_space_two_zero_one_one);
        allInfoFilesIds.add(R.raw.november_space_one_zero_comma_space_two_zero_one_one);
        allInfoFilesIds.add(R.raw.november_space_one_four_comma_space_two_zero_one_one);
        allInfoFilesIds.add(R.raw.december_space_nine_comma_space_two_zero_one_one);
        allInfoFilesIds.add(R.raw.december_space_one_seven_comma_space_two_zero_one_one);
        allInfoFilesIds.add(R.raw.december_space_two_zero_one_one);
        allInfoFilesIds.add(R.raw.january_space_two_zero_one_two);
        allInfoFilesIds.add(R.raw.march_space_eight_dash_one_one_comma_space_two_zero_one_two);
        allInfoFilesIds.add(R.raw.march_space_nine_comma_space_two_zero_one_two);
        allInfoFilesIds.add(R.raw.april_space_one_six_comma_space_two_zero_one_two);
        allInfoFilesIds.add(R.raw.april_space_two_three_comma_space_two_zero_one_two);
        allInfoFilesIds.add(R.raw.may_space_one_eight_comma_space_two_zero_one_two);
        allInfoFilesIds.add(R.raw.may_space_one_nine_comma_space_two_zero_one_two);
        allInfoFilesIds.add(R.raw.may_space_two_four_comma_space_two_zero_one_two);
        allInfoFilesIds.add(R.raw.september_space_one_seven_comma_space_two_zero_one_two);
        allInfoFilesIds.add(R.raw.september_space_two_six_comma_space_two_zero_one_two);
        allInfoFilesIds.add(R.raw.october_space_four_comma_space_two_zero_one_two);
        allInfoFilesIds.add(R.raw.october_space_one_eight_comma_space_two_zero_one_two);
        allInfoFilesIds.add(R.raw.november_space_two_nine_dash_december_space_one_comma_space_two_zero_one_two);
        allInfoFilesIds.add(R.raw.january_space_two_zero_one_three);
        allInfoFilesIds.add(R.raw.may_space_two_zero_one_three);
        allInfoFilesIds.add(R.raw.may_space_two_two_comma_space_two_zero_one_three);
        allInfoFilesIds.add(R.raw.june_space_one_zero_dash_two_four_comma_space_two_zero_one_three);
        allInfoFilesIds.add(R.raw.june_dash_august_space_two_zero_one_three);
        allInfoFilesIds.add(R.raw.september_space_eight_comma_space_two_zero_one_three);
        allInfoFilesIds.add(R.raw.october_space_two_zero_one_three);
        allInfoFilesIds.add(R.raw.october_space_one_one_comma_space_two_zero_one_three);
        allInfoFilesIds.add(R.raw.october_space_one_one_comma_space_two_zero_one_three_duplicate_one);
        allInfoFilesIds.add(R.raw.december_space_one_three_comma_space_two_zero_one_three);
        allInfoFilesIds.add(R.raw.february_space_nine_comma_space_two_zero_one_four);
        allInfoFilesIds.add(R.raw.march_space_one_two_dash_one_six_comma_space_two_zero_one_four);
        allInfoFilesIds.add(R.raw.march_space_two_eight_comma_space_two_zero_one_four);
        allInfoFilesIds.add(R.raw.may_space_two_zero_comma_space_two_zero_one_four);
        allInfoFilesIds.add(R.raw.september_space_two_zero_one_four);
        allInfoFilesIds.add(R.raw.september_space_two_zero_one_four_duplicate_two);
        allInfoFilesIds.add(R.raw.september_space_two_zero_one_four_duplicate_three);
        allInfoFilesIds.add(R.raw.february_space_six_dash_one_two_comma_space_two_zero_one_five);
        allInfoFilesIds.add(R.raw.march_space_one_one_comma_space_two_zero_one_five);
        allInfoFilesIds.add(R.raw.april_space_one_six_comma_space_two_zero_one_five);
        allInfoFilesIds.add(R.raw.may_space_one_two_comma_space_two_zero_one_five);
        allInfoFilesIds.add(R.raw.may_space_two_zero_one_five);
        allInfoFilesIds.add(R.raw.october_space_two_four_comma_space_two_zero_one_five);
        allInfoFilesIds.add(R.raw.october_comma_space_two_zero_one_five);
        allInfoFilesIds.add(R.raw.november_space_one_zero_comma_space_two_zero_one_five);

        return allInfoFilesIds;
    }

}


